name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: install deps
        run: make install
      - name: lint
        run: make lint

