name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: install deps
        run: make install
      - name: lint
        run: make lint

